ALTER TABLE equipe
ADD COLUMN password VARCHAR(255) NOT NULL AFTER email,
ADD COLUMN rib VARCHAR(50) DEFAULT NULL AFTER password,
ADD COLUMN telephone VARCHAR(30) DEFAULT NULL AFTER rib,
ADD COLUMN adresse VARCHAR(255) DEFAULT NULL AFTER telephone; 